#!/bin/bash


# The requirements for a program are the following
# it must (ONLY) be the number it is run on, followed by a tab and then the time it took to run

NUM=$1
NUMER=$2
FUNC=$3
FILE=$4

for i in `seq 1 $NUM`
do
  for j in `seq 1 $NUMER`
  do
    $FUNC $i >> $i.perf
  done
done
for i in `seq 1 $NUM`
do
  awk "{sum+=\$2} END { print \"$i\" \"\t\" ,sum/NR}" $i.perf >> $FILE
done
