

#Makefile.common is the master makefile for the ivar tests. you should include this
#in all of your sub makefiles


#this must be on one line...each line starts off in a new shell
DIR_ROOT=.
DIR_BIN=.

SCRIPT_DIR=$(CILK_SRC)/cilk_tests/scripts

build: $(wildcard *.cp?{2})
	@echo ${DIR_ROOT}
	@echo ${DIR_BIN}
	cp $(SCRIPT_DIR)/build_directory.sh $(DIR_ROOT)
	./build_directory.sh
	rm build_directory.sh

clean:
	rm -rf build
	
distclean:
	rm -rf build
	rm -rf bin
