#!/bin/bash


# The requirements for a program are the following
# it must (ONLY) be the number it is run on, followed by a tab and then the time it took to run

LB=$1
UPB=$2
NUM_RUNS=$3
FUNC_ONE=$4
FUNC_TWO=$5
FILE=$6

rm -f $FILE
rm -f *.perf

for i in `seq $LB $UPB`
do
  for j in `seq 1 $NUM_RUNS`
  do
    $FUNC_ONE $i >> $i.perf1
    $FUNC_TWO $i >> $i.perf2
  done
done
for i in `seq $LB $UPB`
do
  awk "{sum+=\$2} END { print \"$i\" \"\t\" ,sum/NR \"\t\" ,sum/NR}" $i.perf1 $i.perf2 >> $FILE
done
