
#vars for the tests to compile. run them all with make test
BIN= queue_test.exe

#directory where compiled files wil be put
OUT=bin

#path to run_tests.sh
SCRIPTS="../scripts"

#path from scripts to the current directory
SCRIPT_PREFIX="../queue"

#magic
include ../Makefile.common

