
#vars for the tests to compile. run them all with make test
BIN= ivar1.exe ivar2.exe ivar2B.exe ivar3.exe ivar4.exe ivar5.exe 

#directory where compiled files wil be put
OUT=bin

#path to run_tests.sh
SCRIPTS="../scripts"

#path from scripts to the current directory
SCRIPT_PREFIX="../simple"

#magic
include ../Makefile.common

