
#vars for the tests to compile. run them all with make test
BIN= deadlock_test1.exe deadlock_test3.exe \
	deadlock_test4.exe deadlock_test5.exe  deadlock_test6.exe \
	nested_deadlock.exe interleaved_read_write.exe            \
	nested_deadlock_assignment.exe nested_deadlock_delay_writer.exe \

#directory where compiled files wil be put
OUT=bin

#path to run_tests.sh
SCRIPTS="../scripts"

#path from scripts to the current directory
SCRIPT_PREFIX="../readwrite"

#magic
include ../Makefile.common

